[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.filesystem = spiffs

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -std=gnu++17
    -fno-exceptions
    -fno-rtti

lib_deps =
    fastled/FastLED@^3.6.0
    olikraus/U8g2

[env:native]
platform = native
test_framework = unity
build_flags =
    -std=gnu++17
    -Itest/support
build_src_filter =
    +<Line2D.cpp>
    +<Point2D.cpp>
    +<Lap.cpp>
    +<Sector.cpp>
    +<Track.cpp>
    +<TrackTiming.cpp>
test_build_src = yes