[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; 16MB Flash + 8MB OPI PSRAM 配置
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.filesystem = spiffs

; 啟用 PSRAM
build_flags = 
    -DBOARD_HAS_PSRAM
    -std=gnu++17
    -fno-exceptions
    -fno-rtti

lib_deps = 
    fastled/FastLED@^3.6.0
    olikraus/U8g2
    bblanchon/ArduinoJson@^6.21.3